import { Company } from 'src/types'

import {
    Ada,
    Alexandra,
    Anemone,
    Aria,
    Atlas,
    Bastian,
    Bruno,
    Cassian,
    Claire,
    Claude,
    Dana,
    Dex,
    Elan,
    Emil,
    Ernest,
    Eva,
    Felix,
    Fred,
    Frida,
    Hazel,
    Hugo,
    Ingrid,
    Iris,
    Isabella,
    Jake,
    Jonas,
    Juno,
    Kai,
    Kira,
    Lena,
    Leo,
    Lily,
    Marcus,
    Mark,
    Mateo,
    Max,
    Maya,
    Milo,
    Mira,
    Mounir,
    Nadia,
    Natalie,
    Nico,
    Nina,
    Nova,
    Olivia,
    Otis,
    Ouria,
    Petra,
    Piper,
    Priya,
    Quinn,
    Raphael,
    Reid,
    Remy,
    Renee,
    Rowan,
    Sasha,
    Sophia,
    Sophie,
    Soren,
    Sybilla,
    Tessa,
    Theo,
    Ulrich,
    Ulyss,
    Vera,
    Vince,
    Wren,
    Xavier,
    Zarra,
} from './team-members'

export const Awwwesome = {
    id    : 'awwwesome',
    name  : 'Awwwesome',
    title : 'Web Development Experts',
    description :
        'A web development agency that takes projects from idea to production: product framing, functional analysis, design, frontend and backend development, quality assurance, infrastructure, security and documentation.',
    teams : [
        {
            id          : 'project-management',
            name        : 'Project Management',
            title       : 'Product & Delivery',
            description : 'Frames the product, plans the work and ships releases.',
            teamMembers : [Cassian, Priya, Vince, Ouria],
            parents     : [],
            children    : [
                'functional-analysis',
                'architecture',
                'design',
                'quality-assurance',
                'devops',
                'security',
                'documentation',
            ],
        },
        {
            id    : 'functional-analysis',
            name  : 'Functional Analysis',
            title : 'Requirements & Specifications',
            description :
                'Structures raw ideas and turns them into functional specifications that architecture and design build upon.',
            teamMembers : [Sybilla, Mira],
            parents     : ['project-management'],
            children    : ['architecture', 'design'],
        },
        {
            id    : 'architecture',
            name  : 'Architecture',
            title : 'Software Architecture',
            description :
                'Designs the overall system, the codebase structure and the patterns the developers build upon.',
            teamMembers : [Atlas, Reid, Rowan, Juno, Mateo],
            parents     : ['project-management', 'functional-analysis'],
            children    : ['frontend-developers', 'backend-developers'],
        },
        {
            id    : 'design',
            name  : 'Design',
            title : 'UI/UX & Brand Design',
            description :
                'Designs the user interfaces, the design system, the brand identity and the motion, with accessibility in mind.',
            teamMembers : [Ulyss, Theo, Iris, Elan, Ada],
            parents     : ['project-management', 'functional-analysis'],
            children    : ['frontend-developers'],
        },
        {
            id    : 'frontend-developers',
            name  : 'Frontend Developers',
            title : 'Web & Mobile Frontend',
            description :
                'Builds, reviews and optimizes the web and mobile interfaces, from markup and styles to animations and 3D.',
            teamMembers : [Sophia, Marcus, Mark, Zarra, Wren, Sasha, Jonas, Emil, Kai],
            parents     : ['architecture', 'design'],
            children    : [],
        },
        {
            id    : 'backend-developers',
            name  : 'Backend Developers',
            title : 'Backend, APIs & Data',
            description :
                'Builds and reviews the server-side logic, APIs, databases and data pipelines, and keeps them fast.',
            teamMembers : [Alexandra, Bastian, Ernest, Nadia, Nova, Dana, Tessa],
            parents     : ['architecture'],
            children    : [],
        },
        {
            id    : 'quality-assurance',
            name  : 'Quality Assurance',
            title : 'Testing & Bug Fixing',
            description :
                'Tests the product at every level, reproduces and analyzes bugs, and fixes them at the root.',
            teamMembers : [Raphael, Quinn, Dex, Leo, Remy, Vera, Felix],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'devops',
            name  : 'DevOps',
            title : 'Infrastructure & Operations',
            description :
                'Runs the CI/CD pipelines, the cloud infrastructure, the containers and the monitoring of the product in production.',
            teamMembers : [Jake, Mounir, Milo, Otis, Piper],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'security',
            name  : 'Security',
            title : 'Security & Privacy Compliance',
            description :
                'Audits and remediates security vulnerabilities, and keeps the handling of personal data compliant.',
            teamMembers : [Soren, Kira, Petra, Lena],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'documentation',
            name  : 'Documentation',
            title : 'Technical Writing',
            description :
                'Documents the code, the APIs, the infrastructure and the releases, and onboards new developers.',
            teamMembers : [Fred, Hugo, Ingrid, Hazel, Nina],
            parents     : ['project-management'],
            children    : [],
        },
    ],
} satisfies Company

export const HypeAndGlory = {
    id          : 'hype-and-glory',
    name        : 'Hype & Glory',
    title       : 'Content & Marketing Agency',
    description : 'A content and marketing agency that turns products into stories people share: audience strategy, brand identity, editorial content, growth campaigns and video.',
    teams       : [
        {
            id          : 'strategy',
            name        : 'Strategy',
            title       : 'Audience & Campaign Strategy',
            description : 'Qualifies the audiences, reads the data, and decides which campaigns are worth running.',
            teamMembers : [Cassian, Eva, Sophie, Ouria],
            parents     : [],
            children    : ['brand', 'editorial', 'growth', 'legal'],
        },
        {
            id          : 'brand',
            name        : 'Brand',
            title       : 'Brand Identity & Motion',
            description : 'Crafts the visual identity and the motion language every piece of content speaks.',
            teamMembers : [Iris, Elan],
            parents     : ['strategy'],
            children    : ['video'],
        },
        {
            id          : 'editorial',
            name        : 'Editorial',
            title       : 'Storytelling & Content',
            description : 'Writes, structures and adapts the content, from long stories to punchy summaries, for every culture it targets.',
            teamMembers : [Olivia, Frida, Renee, Anemone, Isabella],
            parents     : ['strategy'],
            children    : ['video'],
        },
        {
            id          : 'growth',
            name        : 'Growth',
            title       : 'SEO, Conversion & Channels',
            description : 'Gets the content found, clicked and converted, through search, landing pages, emails and social media.',
            teamMembers : [Xavier, Lily, Claire, Natalie],
            parents     : ['strategy'],
            children    : [],
        },
        {
            id          : 'video',
            name        : 'Video',
            title       : 'Video Production',
            description : 'Scripts the videos, building on the editorial content and the brand motion.',
            teamMembers : [Maya],
            parents     : ['brand', 'editorial'],
            children    : [],
        },
        {
            id          : 'legal',
            name        : 'Legal',
            title       : 'Claims & Intellectual Property',
            description : 'Checks that claims, trademarks and borrowed content will not come back to bite.',
            teamMembers : [Aria],
            parents     : ['strategy'],
            children    : [],
        },
    ],
} satisfies Company

export const OverfittingRoom = {
    id          : 'overfitting-room',
    name        : 'The Overfitting Room',
    title       : 'Data & AI Lab',
    description : 'A data and AI lab that turns raw data into models and insights, and explains them in words everyone understands: data engineering, data science, machine learning, platform and governance.',
    teams       : [
        {
            id          : 'management',
            name        : 'Management',
            title       : 'Product & Architecture',
            description : 'Decides which questions are worth answering with data, and designs the system that answers them.',
            teamMembers : [Priya, Atlas, Ouria],
            parents     : [],
            children    : ['data-engineering', 'data-science', 'platform', 'data-governance'],
        },
        {
            id          : 'data-engineering',
            name        : 'Data Engineering',
            title       : 'Pipelines & Databases',
            description : 'Collects, stores and transforms the data reliably, so the data scientists never have to.',
            teamMembers : [Dana, Ernest, Nadia],
            parents     : ['management'],
            children    : ['data-science'],
        },
        {
            id          : 'data-science',
            name        : 'Data Science',
            title       : 'Analysis & Machine Learning',
            description : 'Finds the insights in the data and trains the models, without mistaking noise for signal.',
            teamMembers : [Sophie, Ulrich],
            parents     : ['management', 'data-engineering'],
            children    : ['communication'],
        },
        {
            id          : 'platform',
            name        : 'Platform',
            title       : 'Cloud, Containers & Observability',
            description : 'Runs the infrastructure the pipelines and models live on, and watches it.',
            teamMembers : [Mounir, Milo, Piper],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'data-governance',
            name        : 'Data Governance',
            title       : 'Data Flows & Privacy',
            description : 'Maps where the data flows and keeps its processing compliant with privacy regulations.',
            teamMembers : [Lena, Petra],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'communication',
            name        : 'Communication',
            title       : 'Data Storytelling',
            description : 'Turns the statistics and the models into explanations that non-experts understand and trust.',
            teamMembers : [Claude, Max],
            parents     : ['data-science'],
            children    : [],
        },
    ],
} satisfies Company

export const CodeNecromancers = {
    id          : 'code-necromancers',
    name        : 'The Code Necromancers',
    title       : 'Legacy Code Modernization',
    description : 'A studio that brings legacy codebases back from the dead: it explores them, stabilizes them, modernizes their architecture and dependencies, speeds them up, and hands them over documented.',
    teams       : [
        {
            id          : 'assessment',
            name        : 'Assessment',
            title       : 'Codebase Exploration & Planning',
            description : 'Explores the codebase and its dependencies, and plans the resurrection before anyone touches a line.',
            teamMembers : [Cassian, Mateo, Nico, Ouria],
            parents     : [],
            children    : ['stabilization', 'architecture', 'performance', 'handover'],
        },
        {
            id          : 'stabilization',
            name        : 'Stabilization',
            title       : 'Testing & Bug Fixing',
            description : 'Pins the current behavior down with tests, then reproduces, analyzes and fixes the bugs at their root.',
            teamMembers : [Remy, Vera, Felix, Raphael, Quinn],
            parents     : ['assessment'],
            children    : ['architecture'],
        },
        {
            id          : 'architecture',
            name        : 'Architecture',
            title       : 'Refactoring & Migration',
            description : 'Refactors the architecture and migrates the code to modern frameworks, under the safety net of the tests.',
            teamMembers : [Reid, Rowan, Bruno],
            parents     : ['assessment', 'stabilization'],
            children    : ['performance'],
        },
        {
            id          : 'performance',
            name        : 'Performance',
            title       : 'Performance Optimization',
            description : 'Measures, then removes the bottlenecks the years have piled up, on the backend and in the browser.',
            teamMembers : [Tessa, Leo, Jonas],
            parents     : ['assessment', 'architecture'],
            children    : [],
        },
        {
            id          : 'handover',
            name        : 'Handover',
            title       : 'Documentation & Release',
            description : 'Documents what changed, onboards the next developers, and ships the modernized codebase safely.',
            teamMembers : [Hazel, Nina, Fred, Vince],
            parents     : ['assessment'],
            children    : [],
        },
    ],
} satisfies Company

export const TrustIssues = {
    id          : 'trust-issues',
    name        : 'Trust Issues Inc.',
    title       : 'Security & Compliance Consultancy',
    description : 'A consultancy that trusts nothing and checks everything: security and accessibility audits, remediation, privacy compliance, and clear reports.',
    teams       : [
        {
            id          : 'engagement',
            name        : 'Engagement',
            title       : 'Engagement Lead & Legal',
            description : 'Scopes the engagement, keeps it on track, and frames its legal stakes.',
            teamMembers : [Cassian, Aria, Ouria],
            parents     : [],
            children    : ['audit', 'privacy', 'reporting'],
        },
        {
            id          : 'audit',
            name        : 'Audit',
            title       : 'Security & Accessibility Audit',
            description : 'Hunts down the security vulnerabilities and the accessibility barriers, ranked by severity.',
            teamMembers : [Soren, Ada],
            parents     : ['engagement'],
            children    : ['remediation'],
        },
        {
            id          : 'remediation',
            name        : 'Remediation',
            title       : 'Fixes & Upgrades',
            description : 'Fixes what the audit found, from vulnerable code and dependencies to accessibility issues.',
            teamMembers : [Kira, Emil, Nico],
            parents     : ['audit'],
            children    : [],
        },
        {
            id          : 'privacy',
            name        : 'Privacy',
            title       : 'Data Flows & Privacy Compliance',
            description : 'Maps the personal data flows and checks their compliance with privacy regulations.',
            teamMembers : [Lena, Petra],
            parents     : ['engagement'],
            children    : [],
        },
        {
            id          : 'reporting',
            name        : 'Reporting',
            title       : 'Reports & Documentation',
            description : 'Writes the reports and the documentation, for the engineers as well as the executives.',
            teamMembers : [Ingrid, Max],
            parents     : ['engagement'],
            children    : [],
        },
    ],
} satisfies Company

export const PocketUnicorn = {
    id          : 'pocket-unicorn',
    name        : 'Pocket Unicorn',
    title       : 'Mobile Product Startup',
    description : 'A lean startup that takes a mobile app from idea to app store launch: product, design, engineering, operations and growth, with no one to spare.',
    teams       : [
        {
            id          : 'product',
            name        : 'Product',
            title       : 'Product & Specifications',
            description : 'Structures the idea, prioritizes ruthlessly, and specifies what gets built.',
            teamMembers : [Priya, Mira, Sybilla, Ouria],
            parents     : [],
            children    : ['design', 'engineering', 'ops', 'launch'],
        },
        {
            id          : 'design',
            name        : 'Design',
            title       : 'UI/UX & Design System',
            description : 'Designs the app screens and the design system they are built with.',
            teamMembers : [Ulyss, Theo],
            parents     : ['product'],
            children    : ['engineering'],
        },
        {
            id          : 'engineering',
            name        : 'Engineering',
            title       : 'Mobile, Backend & Testing',
            description : 'Builds the mobile app and its API, and tests it end to end on real devices.',
            teamMembers : [Kai, Alexandra, Nova, Dex],
            parents     : ['product', 'design'],
            children    : [],
        },
        {
            id          : 'ops',
            name        : 'Ops',
            title       : 'CI/CD & Releases',
            description : 'Automates the builds, runs the backend, and ships releases to the stores safely.',
            teamMembers : [Jake, Milo, Vince],
            parents     : ['product'],
            children    : [],
        },
        {
            id          : 'launch',
            name        : 'Launch',
            title       : 'Growth & Acquisition',
            description : 'Gets the app found, downloaded and talked about, through the store listing, landing pages and social media.',
            teamMembers : [Lily, Natalie, Xavier],
            parents     : ['product'],
            children    : [],
        },
    ],
} satisfies Company

export const companies = {
    Awwwesome,
    HypeAndGlory,
    OverfittingRoom,
    CodeNecromancers,
    TrustIssues,
    PocketUnicorn,
} satisfies Record<string, Company>
