import { Company } from 'src/types'

import {
    Ada,
    Alexandra,
    Amara,
    Anemone,
    Aria,
    Atlas,
    Bastian,
    Benedict,
    Bjorn,
    Bruno,
    Camille,
    Carmen,
    Cassian,
    Claire,
    Claude,
    Dana,
    Dario,
    Dex,
    Edgar,
    Edith,
    Elan,
    Emil,
    Ernest,
    Eva,
    Felix,
    Fiona,
    Fred,
    Frida,
    Gideon,
    Harper,
    Hazel,
    Hector,
    Hugo,
    Igor,
    Ingrid,
    Iris,
    Isabella,
    Jake,
    Jonas,
    Juno,
    Kai,
    Kira,
    Klaus,
    Lena,
    Leo,
    Liang,
    Lily,
    Linus,
    Lyra,
    Marcus,
    Margot,
    Marie,
    Mark,
    Mateo,
    Max,
    Maya,
    Milo,
    Mira,
    Mounir,
    Nadia,
    Natalie,
    Nico,
    Nina,
    Nova,
    Olivia,
    Ophelia,
    Oscar,
    Otis,
    Ouria,
    Pablo,
    Pascal,
    Penelope,
    Petra,
    Piper,
    Priya,
    Quentin,
    Quinn,
    Raphael,
    Ravi,
    Reid,
    Remy,
    Renee,
    Rhea,
    Rowan,
    Sasha,
    Selma,
    Sophia,
    Sophie,
    Soren,
    Stella,
    Sybilla,
    Tara,
    Tessa,
    Theo,
    Tobias,
    Ulrich,
    Ulyss,
    Ursula,
    Vera,
    Vince,
    Wanda,
    Wren,
    Xavier,
    Yuki,
    Zarra,
} from './team-members'

export const Awwwesome = {
    id    : 'awwwesome',
    name  : 'Awwwesome',
    title : 'Web Development Experts',
    description :
        'A web development agency that takes projects from idea to production: product framing, functional analysis, design, frontend and backend development, quality assurance, infrastructure, security and documentation.',
    teams : [
        {
            id          : 'project-management',
            name        : 'Project Management',
            title       : 'Product & Delivery',
            description : 'Frames the product, plans the work and ships releases.',
            teamMembers : [Cassian, Priya, Vince, Ouria],
            parents     : [],
            children    : [
                'functional-analysis',
                'architecture',
                'design',
                'quality-assurance',
                'devops',
                'security',
                'documentation',
            ],
        },
        {
            id    : 'functional-analysis',
            name  : 'Functional Analysis',
            title : 'Requirements & Specifications',
            description :
                'Structures raw ideas and turns them into functional specifications that architecture and design build upon.',
            teamMembers : [Sybilla, Mira],
            parents     : ['project-management'],
            children    : ['architecture', 'design'],
        },
        {
            id    : 'architecture',
            name  : 'Architecture',
            title : 'Software Architecture',
            description :
                'Designs the overall system, the codebase structure and the patterns the developers build upon.',
            teamMembers : [Atlas, Reid, Rowan, Juno, Mateo],
            parents     : ['project-management', 'functional-analysis'],
            children    : ['frontend-developers', 'backend-developers'],
        },
        {
            id    : 'design',
            name  : 'Design',
            title : 'UI/UX & Brand Design',
            description :
                'Designs the user interfaces, the design system, the brand identity and the motion, with accessibility in mind.',
            teamMembers : [Ulyss, Theo, Iris, Elan, Ada, Ursula],
            parents     : ['project-management', 'functional-analysis'],
            children    : ['frontend-developers'],
        },
        {
            id    : 'frontend-developers',
            name  : 'Frontend Developers',
            title : 'Web & Mobile Frontend',
            description :
                'Builds, reviews and optimizes the web and mobile interfaces, from markup and styles to animations and 3D.',
            teamMembers : [Sophia, Marcus, Mark, Zarra, Wren, Sasha, Jonas, Emil, Kai],
            parents     : ['architecture', 'design'],
            children    : [],
        },
        {
            id    : 'backend-developers',
            name  : 'Backend Developers',
            title : 'Backend, APIs & Data',
            description :
                'Builds and reviews the server-side logic, APIs, databases and data pipelines, and keeps them fast.',
            teamMembers : [Alexandra, Bastian, Ernest, Nadia, Nova, Dana, Tessa],
            parents     : ['architecture'],
            children    : [],
        },
        {
            id    : 'quality-assurance',
            name  : 'Quality Assurance',
            title : 'Testing & Bug Fixing',
            description :
                'Tests the product at every level, reproduces and analyzes bugs, and fixes them at the root.',
            teamMembers : [Raphael, Quinn, Dex, Leo, Remy, Vera, Felix],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'devops',
            name  : 'DevOps',
            title : 'Infrastructure & Operations',
            description :
                'Runs the CI/CD pipelines, the cloud infrastructure, the containers and the monitoring of the product in production.',
            teamMembers : [Jake, Mounir, Milo, Otis, Piper],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'security',
            name  : 'Security',
            title : 'Security & Privacy Compliance',
            description :
                'Audits and remediates security vulnerabilities, and keeps the handling of personal data compliant.',
            teamMembers : [Soren, Kira, Petra, Lena],
            parents     : ['project-management'],
            children    : [],
        },
        {
            id    : 'documentation',
            name  : 'Documentation',
            title : 'Technical Writing',
            description :
                'Documents the code, the APIs, the infrastructure and the releases, and onboards new developers.',
            teamMembers : [Fred, Hugo, Ingrid, Hazel, Nina],
            parents     : ['project-management'],
            children    : [],
        },
    ],
} satisfies Company

export const HypeAndGlory = {
    id          : 'hype-and-glory',
    name        : 'Hype & Glory',
    title       : 'Content & Marketing Agency',
    description : 'A content and marketing agency that turns products into stories people share: audience strategy, brand identity, editorial content, growth campaigns and video.',
    teams       : [
        {
            id          : 'strategy',
            name        : 'Strategy',
            title       : 'Audience & Campaign Strategy',
            description : 'Qualifies the audiences, reads the data, and decides which campaigns are worth running.',
            teamMembers : [Cassian, Eva, Sophie, Ouria],
            parents     : [],
            children    : ['brand', 'editorial', 'growth', 'legal'],
        },
        {
            id          : 'brand',
            name        : 'Brand',
            title       : 'Brand Identity & Motion',
            description : 'Crafts the visual identity and the motion language every piece of content speaks.',
            teamMembers : [Iris, Elan],
            parents     : ['strategy'],
            children    : ['video'],
        },
        {
            id          : 'editorial',
            name        : 'Editorial',
            title       : 'Storytelling & Content',
            description : 'Writes, structures and adapts the content, from long stories to punchy summaries, for every culture it targets.',
            teamMembers : [Olivia, Frida, Renee, Anemone, Isabella],
            parents     : ['strategy'],
            children    : ['video'],
        },
        {
            id          : 'growth',
            name        : 'Growth',
            title       : 'SEO, Conversion & Channels',
            description : 'Gets the content found, clicked and converted, through search, landing pages, emails and social media.',
            teamMembers : [Xavier, Lily, Claire, Natalie],
            parents     : ['strategy'],
            children    : [],
        },
        {
            id          : 'video',
            name        : 'Video',
            title       : 'Video Production',
            description : 'Scripts the videos, building on the editorial content and the brand motion.',
            teamMembers : [Maya],
            parents     : ['brand', 'editorial'],
            children    : [],
        },
        {
            id          : 'legal',
            name        : 'Legal',
            title       : 'Claims & Intellectual Property',
            description : 'Checks that claims, trademarks and borrowed content will not come back to bite.',
            teamMembers : [Aria],
            parents     : ['strategy'],
            children    : [],
        },
    ],
} satisfies Company

export const OverfittingRoom = {
    id          : 'overfitting-room',
    name        : 'The Overfitting Room',
    title       : 'Data & AI Lab',
    description : 'A data and AI lab that turns raw data into models and insights, and explains them in words everyone understands: data engineering, data science, machine learning, platform and governance.',
    teams       : [
        {
            id          : 'management',
            name        : 'Management',
            title       : 'Product & Architecture',
            description : 'Decides which questions are worth answering with data, and designs the system that answers them.',
            teamMembers : [Priya, Atlas, Ouria],
            parents     : [],
            children    : ['data-engineering', 'data-science', 'platform', 'data-governance'],
        },
        {
            id          : 'data-engineering',
            name        : 'Data Engineering',
            title       : 'Pipelines & Databases',
            description : 'Collects, stores and transforms the data reliably, so the data scientists never have to.',
            teamMembers : [Dana, Ernest, Nadia],
            parents     : ['management'],
            children    : ['data-science'],
        },
        {
            id          : 'data-science',
            name        : 'Data Science',
            title       : 'Analysis & Machine Learning',
            description : 'Finds the insights in the data and trains the models, without mistaking noise for signal.',
            teamMembers : [Sophie, Ulrich],
            parents     : ['management', 'data-engineering'],
            children    : ['communication'],
        },
        {
            id          : 'platform',
            name        : 'Platform',
            title       : 'Cloud, Containers & Observability',
            description : 'Runs the infrastructure the pipelines and models live on, and watches it.',
            teamMembers : [Mounir, Milo, Piper],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'data-governance',
            name        : 'Data Governance',
            title       : 'Data Flows & Privacy',
            description : 'Maps where the data flows and keeps its processing compliant with privacy regulations.',
            teamMembers : [Lena, Petra],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'communication',
            name        : 'Communication',
            title       : 'Data Storytelling',
            description : 'Turns the statistics and the models into explanations that non-experts understand and trust.',
            teamMembers : [Claude, Max],
            parents     : ['data-science'],
            children    : [],
        },
    ],
} satisfies Company

export const CodeNecromancers = {
    id          : 'code-necromancers',
    name        : 'The Code Necromancers',
    title       : 'Legacy Code Modernization',
    description : 'A studio that brings legacy codebases back from the dead: it explores them, stabilizes them, modernizes their architecture and dependencies, speeds them up, and hands them over documented.',
    teams       : [
        {
            id          : 'assessment',
            name        : 'Assessment',
            title       : 'Codebase Exploration & Planning',
            description : 'Explores the codebase and its dependencies, and plans the resurrection before anyone touches a line.',
            teamMembers : [Cassian, Mateo, Nico, Ouria],
            parents     : [],
            children    : ['stabilization', 'architecture', 'performance', 'handover'],
        },
        {
            id          : 'stabilization',
            name        : 'Stabilization',
            title       : 'Testing & Bug Fixing',
            description : 'Pins the current behavior down with tests, then reproduces, analyzes and fixes the bugs at their root.',
            teamMembers : [Remy, Vera, Felix, Raphael, Quinn],
            parents     : ['assessment'],
            children    : ['architecture'],
        },
        {
            id          : 'architecture',
            name        : 'Architecture',
            title       : 'Refactoring & Migration',
            description : 'Refactors the architecture and migrates the code to modern frameworks, under the safety net of the tests.',
            teamMembers : [Reid, Rowan, Bruno],
            parents     : ['assessment', 'stabilization'],
            children    : ['performance'],
        },
        {
            id          : 'performance',
            name        : 'Performance',
            title       : 'Performance Optimization',
            description : 'Measures, then removes the bottlenecks the years have piled up, on the backend and in the browser.',
            teamMembers : [Tessa, Leo, Jonas],
            parents     : ['assessment', 'architecture'],
            children    : [],
        },
        {
            id          : 'handover',
            name        : 'Handover',
            title       : 'Documentation & Release',
            description : 'Documents what changed, onboards the next developers, and ships the modernized codebase safely.',
            teamMembers : [Hazel, Nina, Fred, Vince],
            parents     : ['assessment'],
            children    : [],
        },
    ],
} satisfies Company

export const TrustIssues = {
    id          : 'trust-issues',
    name        : 'Trust Issues Inc.',
    title       : 'Security & Compliance Consultancy',
    description : 'A consultancy that trusts nothing and checks everything: security and accessibility audits, remediation, privacy compliance, and clear reports.',
    teams       : [
        {
            id          : 'engagement',
            name        : 'Engagement',
            title       : 'Engagement Lead & Legal',
            description : 'Scopes the engagement, keeps it on track, and frames its legal stakes.',
            teamMembers : [Cassian, Aria, Ouria],
            parents     : [],
            children    : ['audit', 'privacy', 'reporting'],
        },
        {
            id          : 'audit',
            name        : 'Audit',
            title       : 'Security & Accessibility Audit',
            description : 'Hunts down the security vulnerabilities and the accessibility barriers, ranked by severity.',
            teamMembers : [Soren, Ada],
            parents     : ['engagement'],
            children    : ['remediation'],
        },
        {
            id          : 'remediation',
            name        : 'Remediation',
            title       : 'Fixes & Upgrades',
            description : 'Fixes what the audit found, from vulnerable code and dependencies to accessibility issues.',
            teamMembers : [Kira, Emil, Nico],
            parents     : ['audit'],
            children    : [],
        },
        {
            id          : 'privacy',
            name        : 'Privacy',
            title       : 'Data Flows & Privacy Compliance',
            description : 'Maps the personal data flows and checks their compliance with privacy regulations.',
            teamMembers : [Lena, Petra],
            parents     : ['engagement'],
            children    : [],
        },
        {
            id          : 'reporting',
            name        : 'Reporting',
            title       : 'Reports & Documentation',
            description : 'Writes the reports and the documentation, for the engineers as well as the executives.',
            teamMembers : [Ingrid, Max],
            parents     : ['engagement'],
            children    : [],
        },
    ],
} satisfies Company

export const PocketUnicorn = {
    id          : 'pocket-unicorn',
    name        : 'Pocket Unicorn',
    title       : 'Mobile Product Startup',
    description : 'A lean startup that takes a mobile app from idea to app store launch: product, design, engineering, operations and growth, with no one to spare.',
    teams       : [
        {
            id          : 'product',
            name        : 'Product',
            title       : 'Product & Specifications',
            description : 'Structures the idea, prioritizes ruthlessly, and specifies what gets built.',
            teamMembers : [Priya, Mira, Sybilla, Ouria],
            parents     : [],
            children    : ['design', 'engineering', 'ops', 'launch'],
        },
        {
            id          : 'design',
            name        : 'Design',
            title       : 'UI/UX & Design System',
            description : 'Designs the app screens and the design system they are built with.',
            teamMembers : [Ulyss, Theo, Ursula],
            parents     : ['product'],
            children    : ['engineering'],
        },
        {
            id          : 'engineering',
            name        : 'Engineering',
            title       : 'Mobile, Backend & Testing',
            description : 'Builds the mobile app and its API, and tests it end to end on real devices.',
            teamMembers : [Kai, Alexandra, Nova, Dex],
            parents     : ['product', 'design'],
            children    : [],
        },
        {
            id          : 'ops',
            name        : 'Ops',
            title       : 'CI/CD & Releases',
            description : 'Automates the builds, runs the backend, and ships releases to the stores safely.',
            teamMembers : [Jake, Milo, Vince],
            parents     : ['product'],
            children    : [],
        },
        {
            id          : 'launch',
            name        : 'Launch',
            title       : 'Growth & Acquisition',
            description : 'Gets the app found, downloaded and talked about, through the store listing, landing pages and social media.',
            teamMembers : [Lily, Natalie, Xavier],
            parents     : ['product'],
            children    : [],
        },
    ],
} satisfies Company

export const RespawnPoint = {
    id          : 'respawn-point',
    name        : 'Respawn Point',
    title       : 'Indie Game Studio',
    description : 'An indie game studio that takes a game from pitch to launch: game design, narrative, art and audio, gameplay programming, playtesting, and a community waiting for day one.',
    teams       : [
        {
            id          : 'direction',
            name        : 'Direction',
            title       : 'Production & Vision',
            description : 'Holds the vision of the game, keeps the scope realistic, and ships it.',
            teamMembers : [Cassian, Sybilla, Ouria],
            parents     : [],
            children    : ['game-design', 'art-audio', 'engineering', 'playtesting', 'launch'],
        },
        {
            id          : 'game-design',
            name        : 'Game Design',
            title       : 'Mechanics & Narrative',
            description : 'Designs the core loop, the mechanics, and the story the players live through.',
            teamMembers : [Gideon, Rhea],
            parents     : ['direction'],
            children    : ['art-audio', 'engineering'],
        },
        {
            id          : 'art-audio',
            name        : 'Art & Audio',
            title       : 'Visuals, Motion & Sound',
            description : 'Gives the game its look, its motion, and its sound, so every action feels right.',
            teamMembers : [Iris, Sasha, Elan, Oscar],
            parents     : ['direction', 'game-design'],
            children    : [],
        },
        {
            id          : 'engineering',
            name        : 'Engineering',
            title       : 'Gameplay & Builds',
            description : 'Turns the design into gameplay code, keeps it fast, and automates the builds.',
            teamMembers : [Yuki, Rowan, Tessa, Jake],
            parents     : ['direction', 'game-design'],
            children    : ['playtesting'],
        },
        {
            id          : 'playtesting',
            name        : 'Playtesting',
            title       : 'Playtests & Bug Hunting',
            description : 'Watches real players play, finds what frustrates them, and hunts the bugs down.',
            teamMembers : [Ursula, Raphael, Remy, Dex],
            parents     : ['direction', 'engineering'],
            children    : [],
        },
        {
            id          : 'launch',
            name        : 'Launch',
            title       : 'Trailers & Community',
            description : 'Builds the hype: trailers, social media, and a community waiting for day one.',
            teamMembers : [Maya, Natalie, Camille],
            parents     : ['direction'],
            children    : [],
        },
    ],
} satisfies Company

export const CartBlanche = {
    id          : 'cart-blanche',
    name        : 'Cart Blanche',
    title       : 'E-commerce Agency',
    description : 'An e-commerce agency that builds online stores and fills their carts: storefront, payments, product content, growth marketing, and compliance.',
    teams       : [
        {
            id          : 'management',
            name        : 'Management',
            title       : 'Project & Product',
            description : "Frames the store's goals, prioritizes the work, and keeps every team aligned.",
            teamMembers : [Cassian, Priya, Ouria],
            parents     : [],
            children    : ['storefront', 'payments', 'merchandising', 'growth', 'compliance'],
        },
        {
            id          : 'storefront',
            name        : 'Storefront',
            title       : 'Store Design & Development',
            description : 'Designs and builds the store, from the product pages to the checkout, and keeps it fast.',
            teamMembers : [Carmen, Ulyss, Marcus, Jonas],
            parents     : ['management'],
            children    : ['payments'],
        },
        {
            id          : 'payments',
            name        : 'Payments',
            title       : 'Payments & Orders',
            description : 'Integrates the payments and keeps every order and refund consistent.',
            teamMembers : [Pablo, Alexandra],
            parents     : ['management', 'storefront'],
            children    : [],
        },
        {
            id          : 'merchandising',
            name        : 'Merchandising',
            title       : 'Product Content & Localization',
            description : 'Writes the product pages that sell, and adapts them to every market.',
            teamMembers : [Olivia, Lily, Isabella],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'growth',
            name        : 'Growth',
            title       : 'Acquisition & Retention',
            description : 'Brings the shoppers in and back, through search, ads, emails, and social media, and measures what works.',
            teamMembers : [Xavier, Eva, Claire, Natalie, Sophie],
            parents     : ['management'],
            children    : [],
        },
        {
            id          : 'compliance',
            name        : 'Compliance',
            title       : 'Legal, Privacy & Security',
            description : "Keeps the terms of sale, the customer data, and the store's security in order.",
            teamMembers : [Aria, Petra, Soren],
            parents     : ['management'],
            children    : [],
        },
    ],
} satisfies Company

export const PivotTable = {
    id          : 'pivot-table',
    name        : 'Pivot Table',
    title       : 'Business Strategy Consultancy',
    description : 'A strategy consultancy for founders: it researches the market, shapes the business model, builds the financial model, and turns it all into a pitch that raises money.',
    teams       : [
        {
            id          : 'partners',
            name        : 'Partners',
            title       : 'Strategy & Engagement',
            description : 'Leads the engagement and shapes the business strategy the rest of the work builds on.',
            teamMembers : [Stella, Cassian, Ouria],
            parents     : [],
            children    : ['research', 'product', 'finance', 'pitch', 'legal'],
        },
        {
            id          : 'research',
            name        : 'Research',
            title       : 'Market & Audience Research',
            description : 'Sizes the market, maps the competition, and qualifies the audiences.',
            teamMembers : [Margot, Eva, Sophie],
            parents     : ['partners'],
            children    : ['finance', 'pitch'],
        },
        {
            id          : 'product',
            name        : 'Product',
            title       : 'Product Framing',
            description : 'Turns the strategy into a product scope and a prioritized roadmap.',
            teamMembers : [Priya, Sybilla, Mira],
            parents     : ['partners'],
            children    : [],
        },
        {
            id          : 'finance',
            name        : 'Finance',
            title       : 'Financial Modeling',
            description : 'Turns the business plan into a financial model with honest scenarios.',
            teamMembers : [Benedict],
            parents     : ['partners', 'research'],
            children    : ['pitch'],
        },
        {
            id          : 'pitch',
            name        : 'Pitch',
            title       : 'Pitch Deck & Storytelling',
            description : 'Turns the research and the numbers into a story investors want to fund.',
            teamMembers : [Hector, Olivia, Claude],
            parents     : ['partners', 'research', 'finance'],
            children    : [],
        },
        {
            id          : 'legal',
            name        : 'Legal',
            title       : 'Corporate & Intellectual Property',
            description : 'Frames the legal stakes: company structure, intellectual property, and contracts.',
            teamMembers : [Aria],
            parents     : ['partners'],
            children    : [],
        },
    ],
} satisfies Company

export const PromptAndCircumstance = {
    id          : 'prompt-and-circumstance',
    name        : 'Prompt & Circumstance',
    title       : 'AI Product Studio',
    description : 'An AI product studio that builds LLM-powered products that work beyond the demo: data, retrieval and prompts, evaluations, product engineering, platform, and trust and safety.',
    teams       : [
        {
            id          : 'leadership',
            name        : 'Leadership',
            title       : 'Product & Architecture',
            description : 'Decides which problems deserve an LLM, and designs the system around it.',
            teamMembers : [Priya, Atlas, Ouria],
            parents     : [],
            children    : ['data', 'llm-engineering', 'product-engineering', 'platform', 'trust-and-safety'],
        },
        {
            id          : 'data',
            name        : 'Data',
            title       : 'Data & Machine Learning',
            description : 'Prepares the data the models retrieve and learn from, and analyzes how the product is used.',
            teamMembers : [Dana, Ulrich, Sophie],
            parents     : ['leadership'],
            children    : ['llm-engineering'],
        },
        {
            id          : 'llm-engineering',
            name        : 'LLM Engineering',
            title       : 'Prompts, Retrieval & Evaluation',
            description : 'Designs the prompts, builds the retrieval and agents, and measures their quality.',
            teamMembers : [Lyra, Ravi, Edith],
            parents     : ['leadership', 'data'],
            children    : ['product-engineering'],
        },
        {
            id          : 'product-engineering',
            name        : 'Product Engineering',
            title       : 'Interfaces & APIs',
            description : 'Builds the product around the model: its interface, its APIs, and its user experience.',
            teamMembers : [Ulyss, Marcus, Mark, Alexandra],
            parents     : ['leadership', 'llm-engineering'],
            children    : [],
        },
        {
            id          : 'platform',
            name        : 'Platform',
            title       : 'Deployment & Observability',
            description : 'Deploys the product and traces every model call in production.',
            teamMembers : [Mounir, Milo, Piper],
            parents     : ['leadership'],
            children    : [],
        },
        {
            id          : 'trust-and-safety',
            name        : 'Trust & Safety',
            title       : 'Security, Privacy & Legal',
            description : 'Guards against prompt injection, data leaks, and legal surprises.',
            teamMembers : [Soren, Petra, Lena, Aria],
            parents     : ['leadership'],
            children    : [],
        },
    ],
} satisfies Company

export const ForkYeah = {
    id          : 'fork-yeah',
    name        : 'Fork Yeah',
    title       : 'Open Source & Developer Relations',
    description : 'An open source studio that turns a project into one developers love and contribute to: solid code, great documentation, developer advocacy, and a welcoming community.',
    teams       : [
        {
            id          : 'maintainers',
            name        : 'Maintainers',
            title       : 'Project Stewardship & Releases',
            description : 'Steers the project, decides what gets merged, and ships the releases.',
            teamMembers : [Cassian, Vince, Ouria],
            parents     : [],
            children    : ['core', 'docs', 'community'],
        },
        {
            id          : 'core',
            name        : 'Core',
            title       : 'Code, Tests & CI',
            description : 'Keeps the code clean, tested, up to date, and continuously integrated.',
            teamMembers : [Rowan, Bastian, Raphael, Nico, Jake],
            parents     : ['maintainers'],
            children    : [],
        },
        {
            id          : 'docs',
            name        : 'Docs',
            title       : 'Documentation & Changelogs',
            description : 'Documents the code and the API, onboards contributors, and writes the changelogs.',
            teamMembers : [Fred, Hugo, Nina, Hazel],
            parents     : ['maintainers'],
            children    : ['devrel'],
        },
        {
            id          : 'devrel',
            name        : 'DevRel',
            title       : 'Developer Advocacy',
            description : 'Shows developers what they can build with the project, through tutorials, talks, and videos.',
            teamMembers : [Dario, Max, Maya],
            parents     : ['docs', 'community'],
            children    : [],
        },
        {
            id          : 'community',
            name        : 'Community',
            title       : 'Community & Contributors',
            description : 'Welcomes users and contributors, triages their issues, and keeps the discussions healthy.',
            teamMembers : [Camille, Natalie, Isabella],
            parents     : ['maintainers'],
            children    : ['devrel'],
        },
    ],
} satisfies Company

export const HotfixHotel = {
    id          : 'hotfix-hotel',
    name        : 'Hotfix Hotel',
    title       : 'Incident Response',
    description : 'An incident response team that checks in when production is on fire: it restores the service first, finds the root cause, fixes it for good, and writes the postmortem so it never happens again.',
    teams       : [
        {
            id          : 'command',
            name        : 'Command',
            title       : 'Incident Command',
            description : 'Runs the incident: severity, priorities, roles, timeline, and status updates.',
            teamMembers : [Harper, Ouria],
            parents     : [],
            children    : ['diagnosis', 'mitigation', 'remediation', 'postmortem'],
        },
        {
            id          : 'diagnosis',
            name        : 'Diagnosis',
            title       : 'Observability & Root Cause',
            description : 'Reads the signals, reproduces the failure, and traces it back to its root cause.',
            teamMembers : [Piper, Vera, Remy, Mateo],
            parents     : ['command'],
            children    : ['remediation'],
        },
        {
            id          : 'mitigation',
            name        : 'Mitigation',
            title       : 'Rollback & Stabilization',
            description : 'Stops the bleeding: rollbacks, failovers, scaling, and rate limits.',
            teamMembers : [Otis, Milo, Vince, Nova],
            parents     : ['command'],
            children    : [],
        },
        {
            id          : 'remediation',
            name        : 'Remediation',
            title       : 'Fixes & Regression Tests',
            description : 'Fixes the root cause for good, and pins it down with tests.',
            teamMembers : [Felix, Kira, Tessa, Raphael],
            parents     : ['command', 'diagnosis'],
            children    : [],
        },
        {
            id          : 'postmortem',
            name        : 'Postmortem',
            title       : 'Postmortems & Runbooks',
            description : 'Writes the blameless postmortem and updates the runbooks and changelog.',
            teamMembers : [Bjorn, Ingrid, Hazel],
            parents     : ['command'],
            children    : [],
        },
    ],
} satisfies Company

export const YakShavers = {
    id          : 'yak-shavers',
    name        : 'Yak Shavers',
    title       : 'Platform Engineering & Developer Experience',
    description : 'A platform engineering team that shaves the yaks so product developers do not have to: one-command setups, fast CI, internal tools, and golden paths.',
    teams       : [
        {
            id          : 'platform-leadership',
            name        : 'Platform Leadership',
            title       : 'Platform Strategy',
            description : 'Decides which friction is worth removing, and designs the platform that removes it.',
            teamMembers : [Atlas, Cassian, Ouria],
            parents     : [],
            children    : ['developer-experience', 'ci-cd', 'internal-tools', 'enablement'],
        },
        {
            id          : 'developer-experience',
            name        : 'Developer Experience',
            title       : 'Local Setup & Tooling',
            description : 'Makes the codebase easy to set up, navigate, build, and keep up to date.',
            teamMembers : [Tobias, Juno, Nico],
            parents     : ['platform-leadership'],
            children    : ['enablement'],
        },
        {
            id          : 'ci-cd',
            name        : 'CI/CD',
            title       : 'Pipelines & Deployment',
            description : 'Keeps the pipelines fast and the deployments boring, and watches them.',
            teamMembers : [Jake, Milo, Piper],
            parents     : ['platform-leadership'],
            children    : [],
        },
        {
            id          : 'internal-tools',
            name        : 'Internal Tools',
            title       : 'Admin Panels & CLIs',
            description : 'Builds the self-service tools that replace manual chores and ad hoc database queries.',
            teamMembers : [Wanda, Alexandra, Marcus],
            parents     : ['platform-leadership'],
            children    : [],
        },
        {
            id          : 'enablement',
            name        : 'Enablement',
            title       : 'Documentation & Onboarding',
            description : 'Documents the golden paths and gets new developers productive in days.',
            teamMembers : [Nina, Fred, Hazel, Dario],
            parents     : ['platform-leadership', 'developer-experience'],
            children    : [],
        },
    ],
} satisfies Company

export const TicketToRide = {
    id          : 'ticket-to-ride',
    name        : 'Ticket to Ride',
    title       : 'Customer Support & Success',
    description : 'A customer support team that takes every ticket for a smooth ride: support operations, help center, AI assistant, customer insights, and customer communication.',
    teams       : [
        {
            id          : 'support-leadership',
            name        : 'Support Leadership',
            title       : 'Support Operations',
            description : 'Designs how tickets are triaged, routed, answered, and escalated, and keeps the service levels.',
            teamMembers : [Selma, Cassian, Ouria],
            parents     : [],
            children    : ['knowledge', 'automation', 'insights', 'communication'],
        },
        {
            id          : 'knowledge',
            name        : 'Knowledge',
            title       : 'Help Center',
            description : 'Answers customer questions before they become tickets, in every language the customers speak.',
            teamMembers : [Klaus, Anemone, Renee, Isabella],
            parents     : ['support-leadership'],
            children    : ['automation'],
        },
        {
            id          : 'automation',
            name        : 'Automation',
            title       : 'AI Support Assistant',
            description : 'Builds the support assistant that answers from the help center, and measures its answers.',
            teamMembers : [Lyra, Ravi, Edith],
            parents     : ['support-leadership', 'knowledge'],
            children    : [],
        },
        {
            id          : 'insights',
            name        : 'Insights',
            title       : 'Customer Insights',
            description : 'Turns tickets and feedback into insights the product team can act on.',
            teamMembers : [Sophie, Ursula],
            parents     : ['support-leadership'],
            children    : [],
        },
        {
            id          : 'communication',
            name        : 'Communication',
            title       : 'Customer Communication',
            description : 'Writes the emails and announcements customers actually read.',
            teamMembers : [Claire, Frida],
            parents     : ['support-leadership'],
            children    : [],
        },
    ],
} satisfies Company

export const LostInTranslation = {
    id          : 'lost-in-translation',
    name        : 'Lost in Translation',
    title       : 'Localization Studio',
    description : 'A localization studio that makes sure nothing gets lost in translation: internationalized code, culturally adapted content, local marketing, and local compliance.',
    teams       : [
        {
            id          : 'localization-management',
            name        : 'Localization Management',
            title       : 'Market Prioritization & Coordination',
            description : 'Picks the markets, coordinates the localization, and keeps the voice consistent across cultures.',
            teamMembers : [Cassian, Isabella, Ouria],
            parents     : [],
            children    : ['engineering', 'translation', 'market-adaptation', 'compliance'],
        },
        {
            id          : 'engineering',
            name        : 'Engineering',
            title       : 'Internationalization',
            description : 'Makes the product ready for any language, script, and locale, and tests it.',
            teamMembers : [Liang, Marcus, Quinn],
            parents     : ['localization-management'],
            children    : [],
        },
        {
            id          : 'translation',
            name        : 'Translation',
            title       : 'Translation & Transcreation',
            description : 'Translates and adapts the content, from interface strings to marketing stories.',
            teamMembers : [Amara, Olivia],
            parents     : ['localization-management'],
            children    : ['market-adaptation'],
        },
        {
            id          : 'market-adaptation',
            name        : 'Market Adaptation',
            title       : 'Local Marketing',
            description : 'Adapts the search strategy, the audiences, and the visuals to each market.',
            teamMembers : [Xavier, Eva, Iris],
            parents     : ['localization-management', 'translation'],
            children    : [],
        },
        {
            id          : 'compliance',
            name        : 'Compliance',
            title       : 'Local Law & Privacy',
            description : 'Checks the local legal and privacy requirements of each market.',
            teamMembers : [Aria, Petra],
            parents     : ['localization-management'],
            children    : [],
        },
    ],
} satisfies Company

export const ClassAct = {
    id          : 'class-act',
    name        : 'Class Act',
    title       : 'Online Learning Studio',
    description : 'An online learning studio that turns expertise into courses people finish: instructional design, course content, assessments, video, accessibility, and learner research.',
    teams       : [
        {
            id          : 'academic-direction',
            name        : 'Academic Direction',
            title       : 'Instructional Design',
            description : 'Defines the audience and the learning objectives, and designs the course around them.',
            teamMembers : [Ophelia, Cassian, Ouria],
            parents     : [],
            children    : ['content', 'assessment', 'media', 'accessibility', 'learner-research'],
        },
        {
            id          : 'content',
            name        : 'Content',
            title       : 'Lessons & Tutorials',
            description : 'Writes the lessons, the tutorials, and the summaries, clear for any audience.',
            teamMembers : [Max, Dario, Renee, Anemone],
            parents     : ['academic-direction'],
            children    : ['assessment', 'media'],
        },
        {
            id          : 'assessment',
            name        : 'Assessment',
            title       : 'Quizzes & Exercises',
            description : 'Designs the quizzes and exercises that check the learning objectives were reached.',
            teamMembers : [Quentin],
            parents     : ['academic-direction', 'content'],
            children    : [],
        },
        {
            id          : 'media',
            name        : 'Media',
            title       : 'Video & Motion',
            description : 'Scripts the videos and designs the animations that explain what text cannot.',
            teamMembers : [Maya, Elan],
            parents     : ['academic-direction', 'content'],
            children    : [],
        },
        {
            id          : 'accessibility',
            name        : 'Accessibility',
            title       : 'Accessible Learning',
            description : 'Makes sure every learner can follow the course, whatever their abilities.',
            teamMembers : [Ada, Emil],
            parents     : ['academic-direction'],
            children    : [],
        },
        {
            id          : 'learner-research',
            name        : 'Learner Research',
            title       : 'Learner Feedback & Analytics',
            description : 'Watches how learners progress and where they drop out, to improve the course.',
            teamMembers : [Ursula, Sophie],
            parents     : ['academic-direction'],
            children    : [],
        },
    ],
} satisfies Company

export const PeerPressure = {
    id          : 'peer-pressure',
    name        : 'Peer Pressure',
    title       : 'Research Lab',
    description : 'A research lab that puts every idea under peer pressure: literature review, rigorous study design, data, statistics, ethics, and papers that survive review.',
    teams       : [
        {
            id          : 'principal-investigators',
            name        : 'Principal Investigators',
            title       : 'Research Direction',
            description : 'Frames the research question and designs the study that can answer it.',
            teamMembers : [Marie, Sybilla, Ouria],
            parents     : [],
            children    : ['literature', 'data', 'methods', 'ethics', 'writing'],
        },
        {
            id          : 'literature',
            name        : 'Literature',
            title       : 'Literature Review',
            description : 'Maps what is already known, so the research starts where knowledge ends.',
            teamMembers : [Linus],
            parents     : ['principal-investigators'],
            children    : ['methods'],
        },
        {
            id          : 'data',
            name        : 'Data',
            title       : 'Data Collection & Management',
            description : 'Collects, stores, and documents the data so the analysis can be reproduced.',
            teamMembers : [Dana, Ernest],
            parents     : ['principal-investigators'],
            children    : ['methods'],
        },
        {
            id          : 'methods',
            name        : 'Methods',
            title       : 'Statistics & Modeling',
            description : 'Analyzes the data with the right statistics and models, and says what it does not show.',
            teamMembers : [Claude, Sophie, Ulrich],
            parents     : ['principal-investigators', 'literature', 'data'],
            children    : ['writing'],
        },
        {
            id          : 'ethics',
            name        : 'Ethics',
            title       : 'Research Ethics & Privacy',
            description : 'Checks the consent, privacy, and legal requirements of the research.',
            teamMembers : [Petra, Aria],
            parents     : ['principal-investigators'],
            children    : [],
        },
        {
            id          : 'writing',
            name        : 'Writing',
            title       : 'Papers & Communication',
            description : 'Writes the paper, edits it, and explains the findings to the public.',
            teamMembers : [Max, Edgar, Penelope],
            parents     : ['principal-investigators', 'methods'],
            children    : [],
        },
    ],
} satisfies Company

export const GhostwritersGuild = {
    id          : 'ghostwriters-guild',
    name        : 'Ghostwriters Guild',
    title       : 'Writing & Publishing House',
    description : 'A writing and publishing house that turns ideas into books, newsletters, and long-form content: writing, developmental editing, copy editing, design, and launch.',
    teams       : [
        {
            id          : 'editorial-board',
            name        : 'Editorial Board',
            title       : 'Editorial Direction',
            description : "Shapes the project's promise and structure, and steers it from draft to publication.",
            teamMembers : [Edgar, Cassian, Ouria],
            parents     : [],
            children    : ['writers', 'copy-desk', 'production', 'marketing', 'rights'],
        },
        {
            id          : 'writers',
            name        : 'Writers',
            title       : 'Writing & Storytelling',
            description : 'Writes the manuscript, from story and argument to the perfect summary.',
            teamMembers : [Olivia, Frida, Renee, Rhea],
            parents     : ['editorial-board'],
            children    : ['copy-desk'],
        },
        {
            id          : 'copy-desk',
            name        : 'Copy Desk',
            title       : 'Copy Editing & Proofreading',
            description : 'Catches every error and inconsistency, and adapts the text for other cultures.',
            teamMembers : [Penelope, Isabella],
            parents     : ['editorial-board', 'writers'],
            children    : ['production'],
        },
        {
            id          : 'production',
            name        : 'Production',
            title       : 'Layout & Cover Design',
            description : 'Lays out the content for reading, and designs the cover that sells it.',
            teamMembers : [Anemone, Iris],
            parents     : ['editorial-board', 'copy-desk'],
            children    : [],
        },
        {
            id          : 'marketing',
            name        : 'Marketing',
            title       : 'Book Launch',
            description : 'Launches the publication: social media, newsletters, and discoverability.',
            teamMembers : [Natalie, Claire, Xavier],
            parents     : ['editorial-board'],
            children    : [],
        },
        {
            id          : 'rights',
            name        : 'Rights',
            title       : 'Contracts & Intellectual Property',
            description : 'Handles the contracts, copyrights, and permissions.',
            teamMembers : [Aria],
            parents     : ['editorial-board'],
            children    : [],
        },
    ],
} satisfies Company

export const HirePower = {
    id          : 'hire-power',
    name        : 'Hire Power',
    title       : 'People & Talent Agency',
    description : 'A people and talent agency that helps companies hire well and keep their people: hiring processes, onboarding, policies, and employer brand.',
    teams       : [
        {
            id          : 'people-leadership',
            name        : 'People Leadership',
            title       : 'People Operations',
            description : 'Designs how the company hires, onboards, grows, and takes care of its people.',
            teamMembers : [Pascal, Cassian, Ouria],
            parents     : [],
            children    : ['talent', 'onboarding', 'policy', 'employer-brand'],
        },
        {
            id          : 'talent',
            name        : 'Talent',
            title       : 'Hiring',
            description : 'Designs fair, structured hiring processes, and measures the hiring funnel.',
            teamMembers : [Tara, Sophie],
            parents     : ['people-leadership'],
            children    : ['onboarding'],
        },
        {
            id          : 'onboarding',
            name        : 'Onboarding',
            title       : 'Onboarding & Handbooks',
            description : 'Gets new hires productive and at ease, with clear guides and handbooks.',
            teamMembers : [Nina, Anemone],
            parents     : ['people-leadership', 'talent'],
            children    : [],
        },
        {
            id          : 'policy',
            name        : 'Policy',
            title       : 'Employment Law & Employee Privacy',
            description : 'Checks the policies against employment law and protects employee data.',
            teamMembers : [Aria, Petra],
            parents     : ['people-leadership'],
            children    : [],
        },
        {
            id          : 'employer-brand',
            name        : 'Employer Brand',
            title       : 'Employer Branding',
            description : "Tells the company's story to the candidates it wants to attract.",
            teamMembers : [Olivia, Natalie, Iris],
            parents     : ['people-leadership'],
            children    : [],
        },
    ],
} satisfies Company

export const InternetOfStrings = {
    id          : 'internet-of-strings',
    name        : 'Internet of Strings',
    title       : 'Connected Devices Studio',
    description : 'A connected devices studio that pulls the strings from chip to cloud to app: firmware, IoT cloud, companion app, security, and fleet releases.',
    teams       : [
        {
            id          : 'product',
            name        : 'Product',
            title       : 'Product & System Architecture',
            description : 'Defines the product and designs the system that spans the device, the cloud, and the app.',
            teamMembers : [Priya, Atlas, Ouria],
            parents     : [],
            children    : ['firmware', 'cloud', 'app', 'security', 'fleet-ops'],
        },
        {
            id          : 'firmware',
            name        : 'Firmware',
            title       : 'Embedded Development',
            description : 'Writes the firmware that runs on the device, within its memory and battery budgets.',
            teamMembers : [Fiona, Raphael],
            parents     : ['product'],
            children    : ['cloud'],
        },
        {
            id          : 'cloud',
            name        : 'Cloud',
            title       : 'IoT Cloud & Telemetry',
            description : 'Connects the device fleet to the cloud, and stores and watches its telemetry.',
            teamMembers : [Igor, Nova, Dana, Piper],
            parents     : ['product', 'firmware'],
            children    : ['app'],
        },
        {
            id          : 'app',
            name        : 'App',
            title       : 'Companion App',
            description : 'Builds the mobile app that pairs with the device and controls it, and tests it on real devices.',
            teamMembers : [Kai, Ulyss, Dex],
            parents     : ['product', 'cloud'],
            children    : [],
        },
        {
            id          : 'security',
            name        : 'Security',
            title       : 'Device & Data Security',
            description : "Audits the whole chain, from the device to the cloud, and protects the users' data.",
            teamMembers : [Soren, Kira, Petra],
            parents     : ['product'],
            children    : [],
        },
        {
            id          : 'fleet-ops',
            name        : 'Fleet Ops',
            title       : 'Builds & Over-the-Air Releases',
            description : 'Automates the builds and rolls out firmware updates safely across the fleet.',
            teamMembers : [Jake, Vince],
            parents     : ['product'],
            children    : [],
        },
    ],
} satisfies Company

export const companies = {
    Awwwesome,
    HypeAndGlory,
    OverfittingRoom,
    CodeNecromancers,
    TrustIssues,
    PocketUnicorn,
    RespawnPoint,
    CartBlanche,
    PivotTable,
    PromptAndCircumstance,
    ForkYeah,
    HotfixHotel,
    YakShavers,
    TicketToRide,
    LostInTranslation,
    ClassAct,
    PeerPressure,
    GhostwritersGuild,
    HirePower,
    InternetOfStrings,
} satisfies Record<string, Company>
